// Types of User Profile actions
const GET_USER_PROFILE_DATA_REQUEST = "GET_USER_PROFILE_DATA_REQUEST";
const GET_USER_PROFILE_DATA_SUCCESS = "GET_USER_PROFILE_DATA_SUCCESS";
const GET_USER_PROFILE_DATA_FAILURE = "GET_USER_PROFILE_DATA_FAILURE";

// Types of User Repositories actions
const GET_USER_REPOSITORIES_REQUEST = "GET_USER_REPOSITORIES_REQUEST";
const GET_USER_REPOSITORIES_SUCCESS = "GET_USER_REPOSITORIES_SUCCESS";
const GET_USER_REPOSITORIES_FAILURE = "GET_USER_REPOSITORIES_FAILURE";

export const ActionsTypes = {
  GET_USER_PROFILE_DATA_REQUEST,
  GET_USER_PROFILE_DATA_SUCCESS,
  GET_USER_PROFILE_DATA_FAILURE,
  GET_USER_REPOSITORIES_REQUEST,
  GET_USER_REPOSITORIES_SUCCESS,
  GET_USER_REPOSITORIES_FAILURE
};
